import "bootstrap/dist/css/bootstrap.min.css";

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Container } from "@/components/bootstrap";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Nextjs Image Gallery",
  description:
    "Generated by create next app you can put whatever you want here.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div id="root" className="flex flex-col min-h-screen">
          This div is shared across layouts
        </div>
        <Container>{children}</Container>
      </body>
    </html>
  );
}
